-- 코드를 입력하세요
SELECT T.SALES_DATE, T.PRODUCT_ID, T.USER_ID, T.SALES_AMOUNT
FROM (SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT               FROM ONLINE_SALE AS N
      WHERE YEAR(N.SALES_DATE) = 2022 AND MONTH(N.SALES_DATE) = 3
      UNION
      SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT       FROM OFFLINE_SALE AS F
      WHERE YEAR(F.SALES_DATE) = 2022 AND MONTH(F.SALES_DATE) = 3
     ) AS T
ORDER BY T.SALES_DATE ASC, T.PRODUCT_ID ASC, T.USER_ID ASC


