-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, T.FAVORITES
FROM REST_INFO R
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
            FROM REST_INFO
            GROUP BY FOOD_TYPE) T ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.FAVORITES
ORDER BY R.FOOD_TYPE DESC