-- 코드를 입력하세요
SELECT c.HISTORY_ID, c.CAR_ID, DATE_FORMAT(c.START_DATE, '%Y-%m-%d') AS START_DATE, DATE_FORMAT(c.END_DATE, '%Y-%m-%d') AS END_DATE, IF(DATEDIFF(c.END_DATE, c.START_DATE)+1>=30, '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
WHERE YEAR(c.START_DATE) = 2022 AND MONTH(c.START_DATE) = 9
ORDER BY c.HISTORY_ID DESC