-- 코드를 입력하세요
SELECT F.WAREHOUSE_ID, F.WAREHOUSE_NAME, F.ADDRESS,
        (CASE WHEN F.FREEZER_YN IS NULL THEN 'N'
              ELSE F.FREEZER_YN END) AS FREEZER_YN
FROM FOOD_WAREHOUSE F
WHERE F.ADDRESS LIKE '경기도%'
ORDER BY F.WAREHOUSE_ID