-- 코드를 작성해주세요
SELECT sd.ROUTE AS ROUTE, CONCAT(SUM(ROUND(sd.D_BETWEEN_DIST, 1)), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(SUM(sd.D_BETWEEN_DIST)/COUNT(sd.D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE sd
GROUP BY sd.ROUTE
ORDER BY SUM(ROUND(sd.D_BETWEEN_DIST, 1)) DESC