-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT(U.USER_ID)) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT(U.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO U
                                    WHERE YEAR(U.JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO U
INNER JOIN ONLINE_SALE S USING (USER_ID)
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY 1, 2