-- 코드를 입력하세요
SELECT T.CAR_ID, T.AVAILABILITY
FROM ((SELECT CAN.CAR_ID, '대여중' AS AVAILABILITY
       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CAN
       WHERE CAN.CAR_ID IN (SELECT C.CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                            WHERE C.START_DATE <= '2022-10-16' AND C.END_DATE >= '2022-10-16')
       GROUP BY CAN.CAR_ID
       ORDER BY CAN.CAR_ID DESC)

       UNION

      (SELECT CANNOT.CAR_ID, '대여 가능' AS AVAILABILITY
       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CANNOT
       WHERE CANNOT.CAR_ID NOT IN (SELECT C.CAR_ID
                                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                                   WHERE C.START_DATE <= '2022-10-16' AND C.END_DATE >= '2022-10-16')
       GROUP BY CANNOT.CAR_ID
       ORDER BY CANNOT.CAR_ID DESC)) T

ORDER BY T.CAR_ID DESC
