-- 코드를 입력하세요
SELECT SH.HISTORY_ID AS HISTORY_ID, ROUND((DATEDIFF(SH.END_DATE, SH.START_DATE)+1)*SC.DAILY_FEE*(1-IFNULL(SP.DISCOUNT_RATE, 0)*0.01), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR SC
INNER JOIN (SELECT *, (CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
                            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
                            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
                            ELSE NULL
                      END) AS DURATION_TYPE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) SH ON SC.CAR_ID = SH.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN SP ON SC.CAR_TYPE = SP.CAR_TYPE AND SH.DURATION_TYPE = SP.DURATION_TYPE
WHERE SC.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC