-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
SELECT 0 AS NUM -- 비반복문, 시작점 설정
UNION ALL
SELECT NUM+1 -- 반복 설정
FROM HOURS
WHERE NUM<23) -- 종료점 설정

SELECT H.NUM, IFNULL(COUNT(A.DATETIME), 0) AS COUNT
FROM ANIMAL_OUTS A
RIGHT JOIN HOURS H ON HOUR(A.DATETIME) = H.NUM
GROUP BY H.NUM
ORDER BY H.NUM
