-- 코드를 입력하세요
SELECT DATE_FORMAT(A.DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS A
WHERE DATE_FORMAT(A.DATETIME, '%H:%I') BETWEEN '09:00' AND '19:59'
GROUP BY DATE_FORMAT(A.DATETIME, '%H')
ORDER BY DATE_FORMAT(A.DATETIME, '%H')