-- 코드를 입력하세요
SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE C.CAR_ID IN (SELECT C.CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                   WHERE C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                   GROUP BY C.CAR_ID
                   HAVING COUNT(C.CAR_ID) >= 5)
      AND C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH, C.CAR_ID DESC