-- 코드를 입력하세요
SELECT T.CATEGORY, T.MAX_PRICE, N.PRODUCT_NAME
FROM (SELECT F.CATEGORY, MAX(F.PRICE) AS MAX_PRICE, F.PRODUCT_NAME
      FROM FOOD_PRODUCT F
      GROUP BY F.CATEGORY
      HAVING F.CATEGORY IN ('과자', '국', '김치', '식용유')) T
INNER JOIN FOOD_PRODUCT N ON T.CATEGORY = N.CATEGORY AND T.MAX_PRICE = N.PRICE
ORDER BY T.MAX_PRICE DESC