-- 코드를 작성해주세요
SELECT (CASE
            WHEN EXISTS(SELECT S.CODE FROM SKILLCODES S WHERE D.SKILL_CODE & S.CODE AND S.CATEGORY = 'Front End')
                 AND EXISTS(SELECT S.CODE FROM SKILLCODES S WHERE D.SKILL_CODE & S.CODE AND S.NAME = 'Python') THEN 'A'
            WHEN EXISTS(SELECT S.CODE FROM SKILLCODES S WHERE D.SKILL_CODE & S.CODE AND S.NAME = 'C#') THEN 'B'
            WHEN EXISTS(SELECT S.CODE FROM SKILLCODES S WHERE D.SKILL_CODE & S.CODE AND S.CATEGORY = 'Front End') THEN 'C'
            ELSE NULL
       END) AS 'GRADE',
       D.ID, D.EMAIL
FROM DEVELOPERS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID
